version: '3.8'

services:
  server:
    build: ./server
    container_name: iot_server
    ports:
      - "5000:5000"

  iot-device:
    build: ./iot-device
    container_name: iot_device
    depends_on:
      - server
