version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - my_network

  client:
    build: ./client
    stdin_open: true
    tty: true
    networks:
      - my_network
    depends_on:
      - server

networks:
  my_network:
    driver: bridge
